platform :ios, '9.0'

#忽略引入库的所有警告
inhibit_all_warnings!

target 'JSBaseProject' do

pod 'AFNetworking', '~> 4.0'
pod 'IQKeyboardManager', '~> 6.5'
pod 'Masonry', '~> 1.1.0'
pod 'MBProgressHUD', '~> 1.0'
pod 'MJExtension', '~> 3.2'
pod 'MJRefresh', '~> 3.4'
pod 'SDWebImage', '~> 5.0'

end
